### ISSUE TITLE
Make the build.properties files portable to different machines

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/faban#1]
We want to make portable the Faban build across machines.

**Comment by VincenzoFerme** [comment]
@simonedavico what still remain to do about this issue?

**Comment by simonedavico** [comment]
Since we established that setting up `JAVA_HOME` will always require some tinkering from the user, using `${java.home}` instead of `${env.JAVA_HOME}` is the best we can do to ensure a portable build configuration. 

Users will still need to setup the project for JRE 1.7, but it's not a big deal, since they would have to choose a JRE anyway.

I think we can consider this closed.

**Comment by VincenzoFerme** [comment]
Closed for a new issue about documenting how to setup the project in Eclipse (#5)
